#cloud-config

users:
  - name: tyzbit
    shell: /bin/bash
    groups: [admin]
    ssh_authorized_keys: [github:tyzbit]

install:
  auto: true
  no-format: false
  reboot: true

grub_options:
  extra_cmdline: >-
    pcie_aspm=off
    nvme_core.default_ps_max_latency_us=0
    gfxpayload=800x600x32
    gfxmode=800x600x32

extra-dirs-rootfs: &longhorn [/var/lib/longhorn]

upgrade:
  extra-dirs-rootfs: *longhorn

reset:
  extra-dirs-rootfs: *longhorn

kubevip: { enabled: false }

flux:
  github:
    owner: tyzbit
    repository: fleet-infra
    path: clusters/corpus
    components-extra: image-reflector-controller,image-automation-controller
    network-policy: "false"

stages:
  kairos-install.pre.before:
    - if: "[ -e /dev/sda ]"
      name: "Conditionally partition sda"
      commands:
        - e2label /dev/sda "test"
        - parted --script --machine -- /dev/sda mklabel gpt
        - parted --script --machine -- /dev/sda mkpart primary zfs 1MiB 100%
        - zpool create -f -o ashift=12 rpool /dev/sda
        - zfs create -o mountpoint=none rpool/ROOT
        - zfs create -o mountpoint=/ rpool/ROOT/debian
        - zpool set bootfs=rpool/ROOT/debian rpool

    - if: "[ ! -e /dev/sda ]"
      name: "Conditionally partition nvme0n1"
      commands:
        - parted --script --machine -- /dev/nvme0n1 mklabel gpt
        - parted --script --machine -- /dev/nvme0n1 mkpart primary zfs 1MiB 100%
        - zpool create -f -o ashift=12 rpool /dev/nvme0n1
        - zfs create -o mountpoint=none rpool/ROOT
        - zfs create -o mountpoint=/ rpool/ROOT/debian
        - zpool set bootfs=rpool/ROOT/debian rpool

  after-install-chroot:
    - name: "Install ZFS utils"
      packages:
        - zfsutils-linux

    - name: "Mount ZFS filesystem"
      mounts:
        - [rpool/ROOT/debian, /]

    - name: "Add sensitive config values"
      downloads:
        - url: http://nas.onair/sensitive_configs.yaml
          path: /oem/50_sensitive_configs.yaml
        - url: http://nas.onair/sops_secret.yaml
          path: /var/lib/rancher/k3s/server/manifests/sops-secret.yaml

    - name: "Add cluster-specific manifests from GitHub"
      downloads:
        - url: https://raw.githubusercontent.com/tyzbit/kairos-config/main/clusters/corpus/manifests/tigera-operator.yaml
          path: /var/lib/rancher/k3s/server/manifests/tigera-operator.yaml
        - url: https://raw.githubusercontent.com/tyzbit/kairos-config/main/clusters/corpus/manifests/calico-crds.yaml
          path: /var/lib/rancher/k3s/server/manifests/calico-crds.yaml
        - url: https://raw.githubusercontent.com/tyzbit/kairos-config/main/clusters/corpus/manifests/flux-system-namespace.yaml
          path: /var/lib/rancher/k3s/server/manifests/flux-system-namespace.yaml
        - url: https://raw.githubusercontent.com/tyzbit/kairos-config/main/clusters/corpus/manifests/kubelet-config.yaml
          path: /etc/rancher/k3s/kubelet-config.yaml

    - name: "Set up various kube environment variables"
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        CONTAINERD_ADDRESS: /run/k3s/containerd/containerd.sock
        CONTAINERD_NAMESPACE: k8s.io
