#cloud-config

hostname: master-eu-ams1-1
users:
  - name: master
    shell: /bin/bash
    groups:
      - admin
    passwd: master

k3s:
  enabled: true
  args:
  - --disable=traefik,servicelb,metrics-server
  - --cluster-domain=k3s.tty.pl
  - --flannel-backend=none
  - --cluster-domain=cloud.tty.pl
  - --tls-san=k3s.tty.pl
  - --tls-san=cloud.tty.pl
  - --node-taint=node-role.kubernetes.io/master=true:NoSchedule
  - --node-taint=CriticalAddonsOnly=true:NoExecute

install:
  auto: true
  no-format: false
  reboot: true


stages:
  boot:
    - name: "Configure DNS"
      dns:
        path: /etc/resolv.conf
        nameservers:
          - 91.202.179.30
          - 91.202.178.13
          - 208.67.222.222
          - 8.8.8.8

    - name: "Configure NTP"
      ntp:
        servers:
          - 0.pl.pool.ntp.org
          - 1.pl.pool.ntp.org
          - 2.pl.pool.ntp.org
          - 3.pl.pool.ntp.org
  kairos-install.pre.before:
    - if: "[ -e /dev/sda ]"
      name: "Conditionally partition sda"
      commands:
        - |
          e2label /dev/sda "test"
          parted --script --machine -- /dev/sda mklabel gpt
      layout: &layout
        device:
          path: test
        expand_partition:
          size: 0 # All available space
        add_partitions:
          # -- All sizes bellow are in MB
          - fsLabel: COS_OEM
            size: 64
            pLabel: oem
          # -- https://github.com/kairos-io/kairos/issues/1265#issuecomment-1621433780
          - fsLabel: COS_ACTIVE
            size: &os-size 8500
            pLabel: system
          - fsLabel: COS_RECOVERY
            size: *os-size
            pLabel: recovery
          - fsLabel: COS_STATE
            size: 18000
            pLabel: state
          - fsLabel: COS_PERSISTENT
            pLabel: persistent
            size: 25000
            filesystem: "ext4"










     

