#cloud-config

hostname: metal-{{ trunc 4 .MachineID }}
users:
- name: kairos
  # Change to your pass here
  passwd: kairos
  ssh_authorized_keys:
  # Add your github user here!
  - github:mudler

k3s-agent:
  enabled: true
  env:
    K3S_TOKEN: K106aea14c9769516ffe0d9cf8b83a94170c7aecedacc8066a212cfb6b4516e956e::server:492057b7f62425fa7d8d1921ffcf3772
    K3S_URL: https://192.168.23.209:6443



install:
  auto: true
  no-format: false
  reboot: true


stages:
  # -- If a node has /dev/sda, use that. Otherwise use /dev/nvme0n1
  kairos-install.pre.before:
    - if: "[ -e /dev/sdb ]"
      name: "Conditionally partition sdb"
      commands:
        - |
          e2label /dev/sdb "test"
          parted --script --machine -- /dev/sdb mklabel gpt
      layout: &layout
        device:
          path: test
        expand_partition:
          size: 0 # All available space
        add_partitions:
          # -- All sizes bellow are in MB
          - fsLabel: COS_OEM
            size: 64
            pLabel: oem
          # -- https://github.com/kairos-io/kairos/issues/1265#issuecomment-1621433780
          - fsLabel: COS_ACTIVE
            size: &os-size 8500
            pLabel: system
          - fsLabel: COS_RECOVERY
            size: *os-size
            pLabel: recovery
          - fsLabel: COS_STATE
            size: 18000
            pLabel: state
          - fsLabel: COS_PERSISTENT
            pLabel: persistent
            size: 25000
            filesystem: "ext4"






     
